### ISSUE TITLE
VSCode 1.24.0 issues

### ISSUE THREAD

**Issue by sd3z** [dvonessen/aws-cloudformation-yaml#5]
Recently updated to 1.24.0 version of vscode and I've noticed that all functions like !Sub and !Ref is being hightlighted as an error as  ` unknown tag <!Sub>`

Has anyone else had an issue with this?

**Comment by bitfoo1** [comment]
Hello @sd3z,
yes, I know this issue. But it is not because of this extension.
Do you have an extension installed that will check your yaml files? Like YAML Support by Red Hat?
See: https://github.com/redhat-developer/vscode-yaml/issues/76

Hope that helps.

**Comment by bitfoo1** [comment]
I will leave this here, because if someone uses YAML Support by Red Hat will get the `unknown tag <!Sub>`.
You have to use following setting in your user or workspace settings:
```
    "yaml.customTags": [
        "!FindInMap sequence",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Join sequence",
        "!Ref",
        "!Select sequence",
        "!Split sequence",
        "!Sub",
        "!Not sequence",
        "!Equals sequence"
        ]
```

**Comment by pravinsingh** [comment]
...or this to include all the other AWS tags as well:
```
    "yaml.customTags": [
        "!Base64 mapping",
        "!Cidr sequence",
        "!FindInMap sequence",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Join sequence",
        "!Ref", 
        "!Select sequence",
        "!Split sequence",
        "!Sub",
        "!Transform mapping",
        "!Not sequence",
        "!Equals sequence"
    ]
```

**Comment by e4jet** [comment]
Adding this to save someone else the frustration...  I've found that if you don't disable the Ansible plugin, the fix @pravinsingh (and others) provides doesn't work for some reason.

**Comment by pravinsingh** [comment]
@e4jet, a colleague reached out to me today with the same issue, and after a few minutes of struggling I remembered your comment about Ansible plugin, and that saved the day. So, thank you!

I think we should raise this bug, but I'm not sure with whom. The same behavior happens with the other CloudFormation plugin (from @aws-scripting-guy) as well, so this is clearly not a problem with @dthielking's plugin. This could be a bug either in the Ansible plugin, in the Red Hat YAML server, or in VS Code itself.

**Comment by jamman9000** [comment]
If anyone is writing yaml for home assistant, VS code helped me set the custom tags properly:
```
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.minimap.enabled": true,
    "update.showReleaseNotes": false,
    "yaml.customTags": [
        "!secret scalar",
        "!include scalar",
        "!include_dir_merge_named scalar"
    ]
}
```

"scalar" allows regular names (like folder names)
