### ISSUE TITLE
Comments should be un-indented

### ISSUE THREAD

**Issue by felipe1982** [dvonessen/aws-cloudformation-yaml#6]
```
thing1:
    thing2:
        # comment
```
should be
```
thing1:
    thing2:
    # comment
```

**Comment by bitfoo1** [comment]
Hello @felipe1982 I don't get you point. Could you be more clear an maybe show me the issue in the source?

**Comment by felipe1982** [comment]
When I press the `#` key, it should unindent the line, to look like example # 2 above. Currently looks like # 1 above.

**Comment by bitfoo1** [comment]
Ok I see, but I cannot reproduce it. If I am doing the same thing like you I get following.
```
thing1:
thing2:
# comment
```
Are you using any other extension like a yaml linter?
Did you try to disable all extensions?
Enable each extension regarding this topic one by one and test if the indention will be comming from any other extension. 
If you want append your extensions here so I can try it as well.

**Comment by felipe1982** [comment]
I think I had vscode set to autoindent yaml `true`. Closing.
