### ISSUE TITLE
Exclamation point still remains

### ISSUE THREAD

**Issue by felipe1982** [dvonessen/aws-cloudformation-yaml#7]
When typing `!Tag` (or any other ! command) and pressing either Tab or Enter, the output is correct, but the `!` remains.

![image](https://user-images.githubusercontent.com/275621/43138576-adea467e-8f92-11e8-861b-7c512d76c4ec.png)

**Comment by bitfoo1** [comment]
I cannot reproduce it. If I am typing !Tag I do not get any suggestions from Intelisense. 
As the documentation says you only have to type `Tag` instead of `!Tag`.
All commands beginning with an exclamation mark are CloudFormation intrinsic functions, therefore you have to type e.g. `!Sub` or `!FindInMap`.
Hope that helps.

**Comment by felipe1982** [comment]
The documentation does not say what is required to achieve the outcomes.

The first picture is when using `!` (a menu appears)
![2018-07-28 20_35_01-deleteme yml - workspace-vff workspace - visual studio code](https://user-images.githubusercontent.com/275621/43355785-080ad216-92a6-11e8-8782-8ff1227a0f19.jpg)


The second picture is _without_ `!` (no menu appears)
![2018-07-28 20_35_10-deleteme yml - workspace-vff workspace - visual studio code](https://user-images.githubusercontent.com/275621/43355790-151465bc-92a6-11e8-8fe8-92ab7cde3acd.jpg)

I am on windows 10

I have named the file `.yml` and verified that the language is `YAML`

---
Update: I think I have to press `Ctrl + Space` to get the menu to appear. how can I make it automatic?

**Comment by bitfoo1** [comment]
I cannot reproduce it. If I use a new file with suffix .yml and set filetype to YAML I directly become suggestions if I type `AWS`.
Maybe you should check your User and Workspace settings for entries like. 
```JSON
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },
"[yaml]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2,
    "editor.quickSuggestions": {
      "other": true,
      "comments": false,
      "strings": true
    },
    "editor.autoIndent": false
  }
```

**Comment by bitfoo1** [comment]
@felipe1982 have you found a solution for that issue? Or why do you close it?

**Comment by felipe1982** [comment]
I think it must be my fault. I'll reopen if I discover an issue with your extension. I like it a lot.

**Comment by bitfoo1** [comment]
Thank you. I you found a solution please let me know. Maybe someone else has this kind of problem.
